### ISSUE TITLE
Document common usage patterns

### ISSUE THREAD

**Issue by Stratus3D** [Stratus3D/eflambe#12]
It occurred to me today that a set of usage patterns or a "cookbook" for eflambe might be useful.

For example, today I wanted to profile a whole Phoenix pipeline. This did the trick:
```
:eflambe.capture({Phoenix.Endpoint.Cowboy2Handler, :init, 2}, 1, [open: :speedscope])
```

**Comment by Zabrane** [comment]
@Stratus3D can't agree more on the {{Cookbook}} usefulness. I will certainly contribute some real examples.

**Comment by Stratus3D** [comment]
Awesome! Thanks. Feel free to use this issue document them as you come across them. I'll eventually extract them out into a document somewhere.

**Comment by Stratus3D** [comment]
@TheFirstAvenger and anyone else, I'd love to get document some of the common patterns you use with eflambe!

**Comment by TheFirstAvenger** [comment]
@Stratus3D We use `:cowboy_hander.execute/2` in [Flame On](https://dockyard.com/blog/2022/02/22/profiling-elixir-applications-with-flame-graphs-and-flame-on)

**Comment by Stratus3D** [comment]
Closing for now as this isn't something I'm planning on documenting right now. I still welcome comments documenting common usage patterns if anyone who comes across this has something more to share!
