### ISSUE TITLE
Update hex package to newest version with newest changes

### ISSUE THREAD

**Issue by StevenBlitz** [Stratus3D/eflambe#18]
Hello!

I noticed that on the hex package site the newest version, 0.2.3 doesn't include the newest changes that were merged about two months ago. 

Would it be possible to update the package to 0.2.4 and includes those changes?

Open up a PR: #19 that should update some of versions to the next one.

Thanks!

**Comment by Stratus3D** [comment]
Hi @StevenBlitz, good catch. I should tag a new patch version. I'll tag and push in a few minutes.
