### ISSUE TITLE
Add support for older Erlang versions

### ISSUE THREAD

**Issue by codeadict** [Stratus3D/eflambe#21]
Currently eflambe fails to compile on older Erlang/OTP versions, i've personally tested in 18 and 19. I've identified the usage of the new logger and new `gen_server` callbacks like `handle_continue` to be the problem. This tool is incredibly valuable and would be handy to have for people working on legacy codebases. I can contribute this change but wanted to check if this is something the authors will be interested since it will add some workarounds that are not so beautiful.

**Comment by Stratus3D** [comment]
@codeadict is this still something you need?

**Comment by Stratus3D** [comment]
A contribution is still welcome here - it should be easy enough to get working on Erlang 18 and 19 with minimal effort. So far no one else has requested support for older versions so I'm closing this issue.
