### ISSUE TITLE
Endless spew of unexpected trace event

### ISSUE THREAD

**Issue by aselder** [Stratus3D/eflambe#37]
I'm using eflambe on my Phoenix project, Elixir 1.14.2, Erlang 25.1.2

and I'm getting a endless spew of unexpected trace event:

```[info] Received unexpected trace event: {:trace_ts, #PID<0.1691.0>, :return_to, {:orddict, :merge, 3}, {1669, 921967, 417448}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.1691.0>, :return_to, {:erl_lint, :head, 4}, {1669, 921967, 417470}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.1691.0>, :return_to, {:erl_lint, :"-remove_non_visible/1-lc$^0/1-0-", 1}, {1669, 921967, 417558}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.1691.0>, :return_to, {:erl_lint, :"-remove_non_visible/1-lc$^0/1-0-", 1}, {1669, 921967, 417559}}
[info] Received unexpected trace event: {:trace_ts, #PID<0.1691.0>, :return_to, {:erl_lint, :"-remove_non_visible/1-lc$^0/1-0-", 1}, {1669, 921967, 417560}}
```

**Comment by Stratus3D** [comment]
@aselder what version of eflambe are you using? I think this was fixed but maybe not. Also, what options did you pass to eflambe when you got this output?

**Comment by aselder** [comment]
@Stratus3D I was using 0.2.5. I called eflambe from inside `iex -S mix phx.server` session using `:eflambe.capture({:cowboy_handler, :execute, 2})`.

Thanks!

**Comment by aselder** [comment]
It looks like the code to handle :return_to is commented out so it's falling through to the unexpected case.

**Comment by Stratus3D** [comment]
Thanks, I will investigate this. In the meantime you could update to version 0.3.0. That version was pushed to hex.pm but not Github. I will fix that this evening.

**Comment by ollien** [comment]
I'm seeing something similar, even on 0.3.0

```
$ elixir --version
Erlang/OTP 24 [erts-12.3.2.6] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.14.1 (compiled with Erlang/OTP 24)
```

**Comment by ollien** [comment]
I did some investigating, and I think I found the commented code mentioned above. I think the fix is just as simple as this, but I'm not sure the implications of doing this (though I do seem to get a flamegraph generated!)

```diff
diff --git a/src/eflambe_brendan_gregg.erl b/src/eflambe_brendan_gregg.erl
index 63ad0b9..63004fa 100644
--- a/src/eflambe_brendan_gregg.erl
+++ b/src/eflambe_brendan_gregg.erl
@@ -116,8 +116,8 @@ handle_trace_event({trace_ts, _Pid, gc_major_end, _Stats, _TS}, #state{} = State
     {ok, State};
 
 % I don't think I need to worry about these traces
-%handle_trace_event({trace_ts, _Pid, return_to, _MFA, _TS}, State) ->
-%    State;
+handle_trace_event({trace_ts, _Pid, return_to, _MFA, _TS}, State) ->
+    {ok, State};
 
 handle_trace_event(TraceEvent, State) ->
     logger:info("Received unexpected trace event: ~w", [TraceEvent]),
```

**Comment by gmile** [comment]
I can confirm was seeing exactly the same issue when building a flamegraph for a controller action. Applying the patch above did help to resolve it :+1:
